# Generated by Django 5.0.1 on 2024-01-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(choices=[('DR.Kumar-Cardialogist', 'DR.Kumar-Cardialogist'), ('DR.Vijayalakshmi-ENT Specialist', 'DR.Vijayalakshmi-ENT Specialist'), ('DR.Rajesh-Dentist', 'DR.Rajesh-Dentist'), ('DR.Lakshmi-Gynecologist', 'DR.Lakshmi-Gynecologist'), ('DR.Lakshmi-Gynecologist', 'DR.Lakshmi-Gynecologist')], default='DR.Kumar-Cardialogist', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Doctor care', 'Doctor care'), ('Nursing care', 'Nursing care'), ('Medical social services', 'Medical social services'), ('Homemaker or basic assistance care', 'Homemaker or basic assistance care')], default='Doctor care', max_length=50),
        ),
    ]
